<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>WiFiCat</AssemblyName>
    <RootNamespace>WiFiCat.Windows</RootNamespace>
    <Version>1.8.1</Version>
    <AssemblyVersion>1.8.1.0</AssemblyVersion>
    <FileVersion>1.8.1.0</FileVersion>
  </PropertyGroup>
</Project>
